
//Test Routes


//All currencies
GET http://localhost:3000/currency

###

//All active currencies
GET http://localhost:3000/currency/active

###

//Get list of all available currency pairs
GET http://localhost:3000/currency/pairs

###

//Get all available pair order types
GET http://localhost:3000/currency/ordertypes

###

//Get order types of a pair
GET http://localhost:3000/currency/SOLZAR/ordertypes

###

//Get market summary
GET http://localhost:3000/currency/marketsummary

###

//Get market summary of (BTCZAR) pair
GET http://localhost:3000/currency/XEMBTC/marketsummary